### ISSUE TITLE
Enums are no longer getting extracted to a separate schema in certain cases

### ISSUE THREAD

**Issue by IMax153** [tim-smart/openapi-gen#22]
I think this is because the OpenAPI spec that OpenAI is using now uses `allOf` to combine components together, so in the generator we lose track of what is supposed to be extracted into a separate enum and what should be inlined.

For example, `CreateChatCompletionRequest` now looks like:

```yaml
    CreateChatCompletionRequest:
      allOf:
        - $ref: "#/components/schemas/CreateModelResponseProperties"
        - type: object
          properties:
          # ...
```

and `CreateModelResponseProperties`:

```yaml
 CreateModelResponseProperties:
      allOf:
        - $ref: "#/components/schemas/ModelResponseProperties"
```

and then finally `ModelResponseProperties`, which is the thing that actually contains the `enum`:

```yaml
    ModelResponseProperties:
      type: object
      properties:
        model:
          anyOf:
            - type: string
            - type: string
              enum:
              # ...
```

Example of generated OpenAI code showing the inlined enum:

![Image](https://github.com/user-attachments/assets/6e183a28-4cc6-4397-b339-f0d18aed02dc)
